:memo: add bitbrain tutorials
Calinou/awesome-godot pull request #157
Opened 2021-01-17 10:01 UTC by bitbrain

![thumbnail](https://user-images.githubusercontent.com/822035/104837197-dc619780-58aa-11eb-9de8-a4005b5bdcfd.png)

Hello everyone!

My name is Miguel (aka [bitbrain](https://www.youtube.com/channel/UCZDjQltHRNiXIYXMBeLDleA)) and I recently started doing devlogs and tutorials! I added my name to the list as I aim to produce monthly new content (devlogs + tutorials) and this might be interesting to some folks for sure.

2021-01-17 12:01 UTC, bitbrain commented
The following timed out:
```
⌛ https://itch.io/app
⌛ https://ifiregames.itch.io/stern-flowers-chibifire-com-godot-engine
```
could we re-run the pipeline?

2021-01-20 12:40 UTC, Calinou requested changes

2021-01-20 12:40 UTC, Calinou commented on README.md
> +- [bitbrain](https://youtube.com/bitbraindev) - Devlogs and tutorials about building various concepts with Godot.
This line should be moved between Bitwes's channel and Code with Tom to respect alphabetical order.

2021-01-23 14:55 UTC, bitbrain commented on README.md
> +- [bitbrain](https://youtube.com/bitbraindev) - Devlogs and tutorials about building various concepts with Godot.
fixed.

2021-01-23 15:10 UTC, Calinou approved these changes
Thanks! Congratulations for your first merged pull request :tada:

2021-01-23 15:10 UTC, merged