Add BoxCam2D
Calinou/awesome-godot pull request #215
Opened 2021-09-22 16:55 UTC by samdaiya

2021-09-22 17:18 UTC, Calinou requested changes
Please move the newly added line to follow alphabetical order within the list it was added to.

2021-10-03 16:46 UTC, samdaiya commented
Any update on it ?

2021-10-03 17:41 UTC, Calinou commented on README.md
> +- [BoxCam2D](https://github.com/samdaiya/BoxCam2D) - Simplest way to implement grid based 2D Camera movement (Godot 3.x).
```suggestion
- [BoxCam2D](https://github.com/samdaiya/BoxCam2D) - Simplest way to implement grid-based 2D camera movement (Godot 3.x).
```

2021-10-03 17:41 UTC, Calinou commented on README.md
>  - [Aseprite Wizard](https://github.com/viniciusgerevini/godot-aseprite-wizard) - Plugin for importing animations from Aseprite as SpriteFrames (Godot 3.x).
```suggestion
- [Aseprite Wizard](https://github.com/viniciusgerevini/godot-aseprite-wizard) - Plugin for importing animations from Aseprite as SpriteFrames (Godot 3.x).
- [BoxCam2D](https://github.com/samdaiya/BoxCam2D) - Simplest way to implement grid-based 2D camera movement (Godot 3.x).
```

2021-10-03 18:14 UTC, Calinou approved these changes
Thanks!

2021-10-03 18:14 UTC, merged