Add DialogueEngine
Calinou/awesome-godot pull request #344
Opened 2024-08-06 21:34 UTC by Rubonnek

The plugin has been gathering a small user base organically through the [asset library](https://godotengine.org/asset-library/asset/2598).

2024-08-06 23:30 UTC, Calinou requested changes
Please follow alphabetical order in that list (it should be between CSLocator and Godot Google Play Service).

2024-08-07 13:36 UTC, Rubonnek commented
> Please follow alphabetical order in that list (it should be between CSLocator and Godot Google Play Service).

Done

2024-08-07 16:05 UTC, Calinou approved these changes
Thanks!

2024-08-07 16:05 UTC, Calinou commented on README.md
> +- [Dialogue Engine](https://github.com/Rubonnek/dialogue-engine) - A minimalistic dialogue engine that fits into your GUI nodes and automatically graphs the branching dialogues for easy debugging.
```suggestion
- [Dialogue Engine](https://github.com/Rubonnek/dialogue-engine) - Minimalistic dialogue engine that fits into your GUI nodes and automatically graphs the branching dialogues for easy debugging.
```

2024-08-07 16:05 UTC, merged